### ISSUE TITLE
Support pattern matching for "input" argument 

### ISSUE THREAD

**Issue by green13** [kriomant/ogrep-rs#6]
It would be cool to support input in grep like format (pattern matching). 

Example: 
```
ogrep substring folder/*
```

**Comment by kriomant** [comment]
Use can use `ogrep -g substring 'folder/*'`.

**Comment by green13** [comment]
It's suitable only for git repositories, not a common solution :)
```
fatal: not a git repository (or any of the parent directories): .git
git grep failed
```

**Comment by kriomant** [comment]
Ok, I've added support for multiple input files.

**Comment by green13** [comment]
Cool. It really works!
